Attribute VB_Name = "modMain"
' ===================================================================
'  Entry points. Prerequisite: this workbook contains a sheet named
'  "Deal Level Inputs" in the standard 28-column layout (generated by
'  the Python app, or pasted / injected by build.vbs).
'
'  Interactive:  Alt+F8 -> BuildAnalysisWorkbook   (or wire to a button)
'  Scripted:     build.bat / build.vbs runs BuildHeadless (no dialogs;
'                errors propagate to the caller as a nonzero exit)
' ===================================================================
Option Explicit

' Interactive run: progress dialogs, errors shown in a message box.
Public Sub BuildAnalysisWorkbook()
    Dim t0 As Double: t0 = Timer
    On Error GoTo fail
    BuildCore
    MsgBox "Built Deal List (" & modBuild.DealCount() & " deals) and " & _
           "Return & Loss Ratios in " & Format(Timer - t0, "0.0") & "s." & vbCrLf & _
           "Remaining tabs: not yet ported (prototype).", vbInformation, "TR Analyzer (VBA)"
    Exit Sub
fail:
    MsgBox "Build failed: " & Err.Description, vbExclamation, "TR Analyzer (VBA)"
End Sub

' Scripted run: no dialogs; an error aborts the script with a message.
Public Sub BuildHeadless()
    BuildCore
End Sub

Private Sub BuildCore()
    Application.ScreenUpdating = False
    Application.Calculation = xlCalculationManual
    On Error GoTo cleanupFail

    If Not SheetExists("Deal Level Inputs") Then
        Err.Raise vbObjectError + 10, , _
            "Sheet 'Deal Level Inputs' not found - paste or import it first."
    End If

    modBuild.BuildDealList
    Application.Calculate                      ' formulas before the cache reads them
    modPivots.BuildReturnLossRatios

    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    Exit Sub
cleanupFail:
    Dim n As Long, d As String
    n = Err.Number: d = Err.Description
    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    Err.Raise n, , d
End Sub

Private Function SheetExists(ByVal name As String) As Boolean
    Dim ws As Worksheet
    On Error Resume Next
    Set ws = ThisWorkbook.Worksheets(name)
    On Error GoTo 0
    SheetExists = Not ws Is Nothing
End Function
