Attribute VB_Name = "modMain"
' ===================================================================
'  Entry point. Prerequisite: this workbook contains a sheet named
'  "Deal Level Inputs" in the standard 28-column layout (generated by
'  the Python app, or pasted from its output).
'
'  Run: Alt+F8 -> BuildAnalysisWorkbook   (or wire it to a button)
' ===================================================================
Option Explicit

Public Sub BuildAnalysisWorkbook()
    Dim t0 As Double: t0 = Timer
    On Error GoTo fail
    Application.ScreenUpdating = False
    Application.Calculation = xlCalculationManual

    If Not SheetExists("Deal Level Inputs") Then
        Err.Raise vbObjectError + 10, , _
            "Sheet 'Deal Level Inputs' not found - paste or import it first."
    End If

    modBuild.BuildDealList
    Application.Calculate                      ' formulas before the cache reads them
    modPivots.BuildReturnLossRatios

    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    MsgBox "Built Deal List (" & modBuild.DealCount() & " deals) and " & _
           "Return & Loss Ratios in " & Format(Timer - t0, "0.0") & "s." & vbCrLf & _
           "Remaining tabs: not yet ported (prototype).", vbInformation, "TR Analyzer (VBA)"
    Exit Sub
fail:
    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    MsgBox "Build failed: " & Err.Description, vbExclamation, "TR Analyzer (VBA)"
End Sub

Private Function SheetExists(ByVal name As String) As Boolean
    Dim ws As Worksheet
    On Error Resume Next
    Set ws = ThisWorkbook.Worksheets(name)
    On Error GoTo 0
    SheetExists = Not ws Is Nothing
End Function
