Attribute VB_Name = "modSpec"
' ===================================================================
'  GENERATED FILE -- do not edit by hand.
'  Source of truth: app/deal_list_spec.py + app/build_output.py
'  Regenerate with:  python3 vba/generate_vba_spec.py
' ===================================================================
Option Explicit

Public Const DL_NCOLS As Long = 74
Public Const IN_NCOLS As Long = 28
Public Const RLR_NPIVOTS As Long = 15

Public Sub LoadDealListSpec(h() As String, f() As String, fmt() As String, tag() As String)
    ReDim h(1 To 74): ReDim f(1 To 74)
    ReDim fmt(1 To 74): ReDim tag(1 To 74)
    h(1) = "Company"
    f(1) = "in:Company"
    tag(1) = "Input"
    h(2) = "Fund"
    f(2) = "in:Fund"
    tag(2) = "Input"
    h(3) = "Fund Currency"
    f(3) = "in:Fund Currency"
    tag(3) = "Input"
    h(4) = "Vintage"
    f(4) = "F:IF((DealLevelInput[[#This Row],[Inv. Date]]=""""),""n/a"",YEAR(G{r}))"
    fmt(4) = "####"
    tag(4) = "Input"
    h(5) = "Status"
    f(5) = "in:Status"
    fmt(5) = "####"
    tag(5) = "Input"
    h(6) = "Inv. Date"
    f(6) = "in:Inv. Date"
    fmt(6) = "dd\-mmm\-yy"
    tag(6) = "Input"
    h(7) = "Exit Date"
    f(7) = "in:Exit Date"
    fmt(7) = "dd\-mmm\-yy"
    tag(7) = "Formula"
    h(8) = "Exit Year"
    f(8) = "FT:IF((DealLevelInput[[#This Row],[Exit Date]]=""""),""n/a"",YEAR(DealLevelInput[[#This Row],[Exit Date]]))"
    fmt(8) = "####"
    tag(8) = "Formula"
    h(9) = "Hold" & Chr(10) & "Period"
    f(9) = "F:IF((DealLevelInput[[#This Row],[Exit Date]]=""""),""n/a"",IF(ISNUMBER(H{r}),H{r}-G{r},NA()-G{r})/365)"
    fmt(9) = "0.0\ ""years"""
    tag(9) = "Formula"
    h(10) = "Hold Period Buckets"
    f(10) = "FT:IF((DealLevelInput[[#This Row],[Inv. Date]]=""""),""n/a"",IF(DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]]<$J$7,$K$7,IF(DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]]<$J$8,$K$8,IF(DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]]<$J$9,$K$9,IF(DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]]<$J$10,$K$10,$K$11)))))"
    fmt(10) = "0.0\ ""years"""
    tag(10) = "Formula"
    h(11) = "Sector"
    f(11) = "in:Sector"
    h(12) = "Geography"
    f(12) = "in:Geography"
    h(13) = "Total IC mlns for Buckets"
    f(13) = "FT:IF((DealLevelInput[[#This Row],[Total Invested Capital (mlns)]]=""""),0,DealLevelInput[[#This Row],[Total Invested Capital (mlns)]])"
    fmt(13) = "###,###,###;\(###,###,###\);""-"""
    h(14) = "Initial InvCap Buckets"
    f(14) = "FT:IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$7,$O$7,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$8,$O$8,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$9,$O$9,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$10,$O$10,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$11,$O$11,$O$12))))))"
    fmt(14) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(15) = "Total Invested Capital (mlns)"
    f(15) = "in:Total Invested Capital (mlns)"
    fmt(15) = "###,###,###;\(###,###,###\);""-"""
    h(16) = "Realized" & Chr(10) & "Value"
    f(16) = "in0:Realized" & Chr(10) & "Value"
    fmt(16) = "###,###,###;\(###,###,###\);""-"""
    h(17) = "Current" & Chr(10) & "Value"
    f(17) = "in:Current" & Chr(10) & "Value"
    fmt(17) = "###,###,###;\(###,###,###\);""-"""
    h(18) = "Total" & Chr(10) & "Value"
    f(18) = "F:IF(AND(Q{r}="""",R{r}=""""),"""",N(Q{r})+N(R{r}))"
    fmt(18) = "###,###,###;\(###,###,###\);""-"""
    h(19) = "Gross" & Chr(10) & "MOIC"
    f(19) = "FT:IFERROR(DealLevelInput[[#This Row],[Total" & Chr(10) & "Value]]/DealLevelInput[[#This Row],[Total Invested Capital (mlns)]],""n/a"")"
    fmt(19) = "0.0\x;\(0.0\x\);""-"""
    h(20) = "MOIC Buckets"
    f(20) = "FT:IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]<=$T$9,$U$9,IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]<=$T$10,$U$10,IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]<=$T$11,$U$11,$U$12))))"
    fmt(20) = "0.0%"
    h(21) = "Performing" & Chr(10) & "(1=Underperform)"
    f(21) = "FT:IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]<1,1,""-"")"
    fmt(21) = "0.0;\(0.0\);""-"""
    h(22) = "InvCapital in Loss Position"
    f(22) = "FT:IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]<1,DealLevelInput[[#This Row],[Total Invested Capital (mlns)]],0)"
    fmt(22) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(23) = "Impaired" & Chr(10) & "Value"
    f(23) = "FT:IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]]<1,(1-DealLevelInput[[#This Row],[Gross" & Chr(10) & "MOIC]])*DealLevelInput[[#This Row],[Total IC mlns for Buckets]],0)"
    fmt(23) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(24) = "Entry EBITDA"
    f(24) = "FT:IF((DealLevelInput[[#This Row],[Entry LTM" & Chr(10) & "EBITDA]]=""""),""n/a"",DealLevelInput[[#This Row],[Entry LTM" & Chr(10) & "EBITDA]])"
    fmt(24) = "###,###,###.0;\(###,###,###.0\);""-"""
    h(25) = "EBITDA Buckets"
    f(25) = "FT:IF(DealLevelInput[[#This Row],[Entry EBITDA]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$4,$AA$4,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$5,$AA$5,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$6,$AA$6,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$7,$AA$7,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$8,$AA$8,$AA$9))))))"
    fmt(25) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(26) = "Entry Revenue"
    f(26) = "FT:IF((DealLevelInput[[#This Row],[Entry LTM Revenue]]=""""),""n/a"",DealLevelInput[[#This Row],[Entry LTM Revenue]])"
    fmt(26) = "###,###,###.0;\(###,###,###.0\);""-"""
    h(27) = "Revenue Buckets"
    f(27) = "FT:IF(DealLevelInput[[#This Row],[Entry Revenue]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$4,$AC$4,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$5,$AC$5,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$6,$AC$6,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$7,$AC$7,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$8,$AC$8,$AC$9))))))"
    fmt(27) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(28) = "Transaction Type"
    f(28) = "in:Transaction Type"
    h(29) = "GP Role"
    f(29) = "in:GP Role"
    h(30) = "Process Type"
    f(30) = "in:Process Type"
    h(31) = "Sourcing Partner"
    f(31) = "in:Sourcing Partner"
    fmt(31) = "0.00%"
    h(32) = "Exit Type"
    f(32) = "in:Exit Type"
    fmt(32) = "0.00%"
    h(33) = "COI Deal (Yes/No)"
    f(33) = "in:COI Deal (Yes/No)"
    fmt(33) = "0.00%"
    h(34) = "Gross" & Chr(10) & "IRR"
    f(34) = "in:Gross" & Chr(10) & "IRR"
    fmt(34) = "0.0%"
    h(35) = "Entry LTM Revenue"
    f(35) = "in:Entry LTM" & Chr(10) & "Revenue"
    fmt(35) = "###,###.0;\(###,###.0\);""-"""
    tag(35) = "Entry"
    h(36) = "Entry LTM" & Chr(10) & "EBITDA"
    f(36) = "in:Entry LTM" & Chr(10) & "EBITDA"
    fmt(36) = "###,###.0;\(###,###.0\);""-"""
    tag(36) = "Entry"
    h(37) = "Entry" & Chr(10) & "EBITDA Margin"
    f(37) = "FT:IFERROR(DealLevelInput[[#This Row],[Entry LTM" & Chr(10) & "EBITDA]]/DealLevelInput[[#This Row],[Entry LTM Revenue]],""n/a"")"
    fmt(37) = "0.0%"
    tag(37) = "Entry"
    h(38) = "Entry" & Chr(10) & "Net Debt"
    f(38) = "in:Entry" & Chr(10) & "Net Debt"
    fmt(38) = "###,###.0;\(###,###.0\);""-"""
    tag(38) = "Entry"
    h(39) = "Entry Leverage"
    f(39) = "FT:IFERROR(DealLevelInput[[#This Row],[Entry" & Chr(10) & "Net Debt]]/DealLevelInput[[#This Row],[Entry LTM" & Chr(10) & "EBITDA]],""n/a"")"
    fmt(39) = "0.0\x;\(0.0\x\);""-"""
    tag(39) = "Entry"
    h(40) = "Entry" & Chr(10) & "Equity" & Chr(10) & "Value"
    f(40) = "F:IF(AND(AP{r}="""",AM{r}=""""),"""",N(AP{r})-N(AM{r}))"
    fmt(40) = "###,###.0;\(###,###.0\);""-"""
    tag(40) = "Entry"
    h(41) = "Entry Enterprise" & Chr(10) & "Value"
    f(41) = "in:Entry Enterprise" & Chr(10) & "Value"
    fmt(41) = "###,###.0;\(###,###.0\);""-"""
    tag(41) = "Entry"
    h(42) = "Entry" & Chr(10) & "EBITDA Multiple"
    f(42) = "FT:IFERROR(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]/DealLevelInput[[#This Row],[Entry LTM" & Chr(10) & "EBITDA]],""n/a"")"
    fmt(42) = "0.0\x"
    tag(42) = "Entry"
    h(43) = "Entry Equity Multiple"
    f(43) = "FT:IFERROR(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]-DealLevelInput[[#This Row],[Entry Leverage]],""n/a"")"
    fmt(43) = "0.0\x"
    tag(43) = "Entry"
    h(44) = "Entry EV Sales Multiple"
    f(44) = "FT:IFERROR(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]/DealLevelInput[[#This Row],[Entry LTM Revenue]],""n/a"")"
    fmt(44) = "0.0\x"
    tag(44) = "Entry"
    h(45) = "Exit LTM" & Chr(10) & "Revenue"
    f(45) = "in:Exit LTM" & Chr(10) & "Revenue"
    fmt(45) = "###,###.0;\(###,###.0\);""-"""
    tag(45) = "Exit"
    h(46) = "Exit LTM" & Chr(10) & "EBITDA"
    f(46) = "in:Exit LTM" & Chr(10) & "EBITDA"
    fmt(46) = "###,###.0;\(###,###.0\);""-"""
    tag(46) = "Exit"
    h(47) = "Exit" & Chr(10) & "EBITDA Margin"
    f(47) = "FT:IFERROR(DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "EBITDA]]/DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "Revenue]],""n/a"")"
    fmt(47) = "0.0%"
    tag(47) = "Exit"
    h(48) = "Exit" & Chr(10) & "Net Debt"
    f(48) = "in:Exit" & Chr(10) & "Net Debt"
    fmt(48) = "###,###.0;\(###,###.0\);""-"""
    tag(48) = "Exit"
    h(49) = "Exit Leverage"
    f(49) = "FT:IFERROR(DealLevelInput[[#This Row],[Exit" & Chr(10) & "Net Debt]]/DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "EBITDA]],""n/a"")"
    fmt(49) = "0.0\x;\(0.0\x\);""-"""
    tag(49) = "Exit"
    h(50) = "Exit" & Chr(10) & "Equity Value"
    f(50) = "FT:IFERROR(DealLevelInput[[#This Row],[Exit Enterprise Value]]-DealLevelInput[[#This Row],[Exit" & Chr(10) & "Net Debt]],""n/a"")"
    fmt(50) = "###,###.0;\(###,###.0\);""-"""
    tag(50) = "Exit"
    h(51) = "Exit Enterprise Value"
    f(51) = "in:Exit Enterprise Value"
    fmt(51) = "###,###.0;\(###,###.0\);""-"""
    tag(51) = "Exit"
    h(52) = "Exit EBITDA Multiple"
    f(52) = "FT:IFERROR(DealLevelInput[[#This Row],[Exit Enterprise Value]]/DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "EBITDA]],""n/a"")"
    fmt(52) = "0.0\x"
    tag(52) = "Exit"
    h(53) = "Exit EV Sales Multiple"
    f(53) = "FT:IFERROR(DealLevelInput[[#This Row],[Exit Enterprise Value]]/DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "Revenue]],""n/a"")"
    fmt(53) = "0.0\x"
    tag(53) = "Exit"
    h(54) = "Valuation Method"
    f(54) = "in:Valuation Method"
    fmt(54) = "0.0\x"
    h(55) = "Entry Enterprise" & Chr(10) & "ValueBuckets"
    f(55) = "FT:IF(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]<=$BA$6,$BB$6,IF(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]<=$BA$7,$BB$7,IF(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]<=$BA$8,$BB$8,IF(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]<=$BA$9,$BB$9,IF(DealLevelInput[[#This Row],[Entry Enterprise" & Chr(10) & "Value]]<=$BA$10,$BB$10,$BB$11))))))"
    fmt(55) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(56) = "Entry Multiple Bucket"
    f(56) = "FT:IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]<=$BC$6,$BD$6,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]<=$BC$7,$BD$7,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]<=$BC$8,$BD$8,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]<=$BC$9,$BD$9,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]<=$BC$10,$BD$10,$BD$11))))))"
    fmt(56) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(57) = "Entry EBITDA Margin Bucket"
    f(57) = "FT:IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Margin]]=""n/a"",""n/a"",IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Margin]]<=$BE$6,$BF$6,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Margin]]<=$BE$7,$BF$7,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Margin]]<=$BE$8,$BF$8,IF(DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Margin]]<=$BE$9,$BF$9,$BF$10)))))"
    fmt(57) = """$""###,###,###;\(""$""###,###,###\);""-"""
    h(58) = "IRR Buckets"
    f(58) = "FT:IF((DealLevelInput[[#This Row],[Gross" & Chr(10) & "IRR]]=""""),""n/a"",IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "IRR]]<=$W$9,$X$9,IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "IRR]]<=$W$10,$X$10,IF(DealLevelInput[[#This Row],[Gross" & Chr(10) & "IRR]]<=$W$11,$X$11,$X$12))))"
    h(59) = "AdjInvCapRevenueCAGR"
    f(59) = "FT:DealLevelInput[[#This Row],[Total IC mlns for Buckets]]"
    fmt(59) = "#,##0"
    h(60) = "Revenue CAGR"
    f(60) = "FT:IFERROR((DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "Revenue]]/DealLevelInput[[#This Row],[Entry LTM Revenue]])^(1/DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]])-1,""n/a"")"
    fmt(60) = "0.0%"
    h(61) = "WghtdRevCAGR"
    f(61) = "FT:IFERROR(DealLevelInput[[#This Row],[Revenue CAGR]]*DealLevelInput[[#This Row],[AdjInvCapRevenueCAGR]],""n/a"")"
    fmt(61) = "#,##0"
    h(62) = "AdjInvCapEBITDAcagr"
    f(62) = "FT:DealLevelInput[[#This Row],[Total IC mlns for Buckets]]"
    fmt(62) = "#,##0"
    h(63) = "EBITDA CAGR"
    f(63) = "FT:IFERROR((DealLevelInput[[#This Row],[Exit LTM" & Chr(10) & "EBITDA]]/DealLevelInput[[#This Row],[Entry EBITDA]])^(1/DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]])-1,""n/a"")"
    fmt(63) = "0.0%"
    h(64) = "WghtdEBITDAcagr"
    f(64) = "FT:IFERROR(DealLevelInput[[#This Row],[EBITDA CAGR]]*DealLevelInput[[#This Row],[AdjInvCapEBITDAcagr]],""n/a"")"
    fmt(64) = "#,##0"
    h(65) = "AdjInvCapEBITDAMargin"
    f(65) = "FT:DealLevelInput[[#This Row],[Total IC mlns for Buckets]]"
    fmt(65) = "#,##0"
    h(66) = "Wgtd Entry EBITDA Margin"
    f(66) = "FT:IFERROR((DealLevelInput[[#This Row],[AdjInvCapEBITDAMargin]]*DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Margin]]),""n/a"")"
    fmt(66) = "#,##0"
    h(67) = "Wgtd Current EBITDA Margin"
    f(67) = "FT:IFERROR((DealLevelInput[[#This Row],[Total IC mlns for Buckets]]*DealLevelInput[[#This Row],[Exit" & Chr(10) & "EBITDA Margin]]),""n/a"")"
    fmt(67) = "#,##0"
    h(68) = "Wghtd Hold Period"
    f(68) = "FT:IFERROR(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]*DealLevelInput[[#This Row],[Hold" & Chr(10) & "Period]],""n/a"")"
    fmt(68) = "#,##0"
    h(69) = "AdjInvCapMultiples"
    f(69) = "FT:IF(OR(DealLevelInput[[#This Row],[Exit EBITDA Multiple]]=0,DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]=0),0,DealLevelInput[[#This Row],[Total IC mlns for Buckets]])"
    fmt(69) = "#,##0"
    h(70) = "WgtdEntryMultiple"
    f(70) = "FT:IFERROR((DealLevelInput[[#This Row],[AdjInvCapMultiples]]*DealLevelInput[[#This Row],[Entry" & Chr(10) & "EBITDA Multiple]]),""n/a"")"
    fmt(70) = "#,##0"
    h(71) = "WghtdExitMultiple"
    f(71) = "FT:IFERROR((DealLevelInput[[#This Row],[AdjInvCapMultiples]]*DealLevelInput[[#This Row],[Exit EBITDA Multiple]]),""n/a"")"
    fmt(71) = "#,##0"
    h(72) = "AdjInvCapLeverage"
    f(72) = "FT:IF(OR(DealLevelInput[[#This Row],[Entry Leverage]]=""n/a"",DealLevelInput[[#This Row],[Exit Leverage]]=""n/a""),0,DealLevelInput[[#This Row],[Total IC mlns for Buckets]])"
    fmt(72) = "#,##0"
    h(73) = "WghtdEntryLeverage"
    f(73) = "FT:IFERROR(DealLevelInput[[#This Row],[AdjInvCapLeverage]]*DealLevelInput[[#This Row],[Entry Leverage]],""n/a"")"
    fmt(73) = "#,##0"
    h(74) = "WghtdExitLeverage"
    f(74) = "FT:IFERROR(DealLevelInput[[#This Row],[AdjInvCapLeverage]]*DealLevelInput[[#This Row],[Exit Leverage]],""n/a"")"
    fmt(74) = "#,##0"
End Sub

Public Sub LoadInputCols(h() As String)
    ReDim h(1 To 28)
    h(1) = "Company"
    h(2) = "Fund"
    h(3) = "Status"
    h(4) = "Fund Currency"
    h(5) = "Inv. Date"
    h(6) = "Exit Date"
    h(7) = "Sector"
    h(8) = "Geography"
    h(9) = "Total Invested Capital (mlns)"
    h(10) = "Realized" & Chr(10) & "Value"
    h(11) = "Current" & Chr(10) & "Value"
    h(12) = "Transaction Type"
    h(13) = "GP Role"
    h(14) = "Process Type"
    h(15) = "Sourcing Partner"
    h(16) = "Exit Type"
    h(17) = "COI Deal (Yes/No)"
    h(18) = "Gross TVPI"
    h(19) = "Gross" & Chr(10) & "IRR"
    h(20) = "Valuation Method"
    h(21) = "Entry LTM" & Chr(10) & "Revenue"
    h(22) = "Entry LTM" & Chr(10) & "EBITDA"
    h(23) = "Entry" & Chr(10) & "Net Debt"
    h(24) = "Entry Enterprise" & Chr(10) & "Value"
    h(25) = "Exit LTM" & Chr(10) & "Revenue"
    h(26) = "Exit LTM" & Chr(10) & "EBITDA"
    h(27) = "Exit" & Chr(10) & "Net Debt"
    h(28) = "Exit Enterprise Value"
End Sub

Public Sub LoadHeaderBlock(refs() As String, vals() As String, isNum() As Boolean, numv() As Double)
    ReDim refs(1 To 128): ReDim vals(1 To 128)
    ReDim isNum(1 To 128): ReDim numv(1 To 128)
    refs(1) = "B2"
    vals(1) = "Deal List"
    refs(2) = "B4"
    vals(2) = "Sponsor/GP:"
    refs(3) = "B5"
    vals(3) = "As of Date:"
    refs(4) = "B6"
    vals(4) = "Currency:"
    refs(5) = "E9"
    vals(5) = "Number of"
    refs(6) = "F9"
    vals(6) = "Realized"
    refs(7) = "E10"
    vals(7) = "Deals"
    refs(8) = "F10"
    vals(8) = "Deals"
    refs(9) = "E11"
    vals(9) = "=COUNTA(DealLevelInput[Company])"
    refs(10) = "F11"
    vals(10) = "=COUNTIF($F$14:$F${LAST},F9)"
    refs(11) = "J6"
    vals(11) = "Hold Period"
    refs(12) = "K6"
    vals(12) = "HP Buckets"
    refs(13) = "J7"
    isNum(13) = True: numv(13) = 2
    refs(14) = "K7"
    vals(14) = "=CONCATENATE(""<="",TEXT(J7,""0""),"" yrs"")"
    refs(15) = "J8"
    isNum(15) = True: numv(15) = 4
    refs(16) = "K8"
    vals(16) = "=CONCATENATE(TEXT(J7,""0""),"" yrs  - "",TEXT(J8,""0""),"" yrs"")"
    refs(17) = "J9"
    isNum(17) = True: numv(17) = 6
    refs(18) = "K9"
    vals(18) = "=CONCATENATE(TEXT(J8,""0""),"" yrs  - "",TEXT(J9,""0""),"" yrs"")"
    refs(19) = "J10"
    isNum(19) = True: numv(19) = 8
    refs(20) = "K10"
    vals(20) = "=CONCATENATE(TEXT(J9,""0""),"" yrs  - "",TEXT(J10,""0""),"" yrs"")"
    refs(21) = "J11"
    isNum(21) = True: numv(21) = 8
    refs(22) = "K11"
    vals(22) = "=CONCATENATE("">="",TEXT(J11,""0""),"" yrs"")"
    refs(23) = "N6"
    vals(23) = "Inv Cap Buckets"
    refs(24) = "O6"
    vals(24) = "Inv Cap Labels"
    refs(25) = "N7"
    isNum(25) = True: numv(25) = 250
    refs(26) = "O7"
    vals(26) = "=CONCATENATE(""<="",TEXT(N7,""$0""),""m"")"
    refs(27) = "N8"
    isNum(27) = True: numv(27) = 500
    refs(28) = "O8"
    vals(28) = "=CONCATENATE(TEXT(N7,""$0""),"" - "",TEXT(N8,""$0""),""m"")"
    refs(29) = "N9"
    isNum(29) = True: numv(29) = 1000
    refs(30) = "O9"
    vals(30) = "=CONCATENATE(TEXT(N8,""$0""),"" - "",TEXT(N9,""$0""),""m"")"
    refs(31) = "N10"
    isNum(31) = True: numv(31) = 1250
    refs(32) = "O10"
    vals(32) = "=CONCATENATE(TEXT(N9,""$0""),"" - "",TEXT(N10,""$0""),""m"")"
    refs(33) = "N11"
    isNum(33) = True: numv(33) = 1500
    refs(34) = "O11"
    vals(34) = "=CONCATENATE(TEXT(N10,""$0""),"" - "",TEXT(N11,""$0""),""m"")"
    refs(35) = "N12"
    vals(35) = "=N11"
    refs(36) = "O12"
    vals(36) = "=CONCATENATE("">="",TEXT(N12,""$0""),""m"")"
    refs(37) = "T8"
    vals(37) = "MOIC Buckets"
    refs(38) = "U8"
    vals(38) = "MOIC Labels"
    refs(39) = "T9"
    isNum(39) = True: numv(39) = 1
    refs(40) = "U9"
    vals(40) = "=CONCATENATE(""<="",TEXT(T9,""0.0x""))"
    refs(41) = "T10"
    isNum(41) = True: numv(41) = 2
    refs(42) = "U10"
    vals(42) = "=CONCATENATE(TEXT(T9,""0.0x""),"" - "",TEXT(T10,""0.0x""))"
    refs(43) = "T11"
    isNum(43) = True: numv(43) = 3
    refs(44) = "U11"
    vals(44) = "=CONCATENATE(TEXT(T10,""0.0x""),"" - "",TEXT(T11,""0.0x""))"
    refs(45) = "T12"
    isNum(45) = True: numv(45) = 3
    refs(46) = "U12"
    vals(46) = "=CONCATENATE("">="",TEXT(T12,""0.0x""))"
    refs(47) = "Z3"
    vals(47) = "EBITDA Buckets"
    refs(48) = "AA3"
    vals(48) = "EBITDA Labels"
    refs(49) = "Z4"
    isNum(49) = True: numv(49) = 0
    refs(50) = "AA4"
    vals(50) = "=CONCATENATE(""<="",TEXT(Z4,""$0""),""m"")"
    refs(51) = "Z5"
    isNum(51) = True: numv(51) = 100
    refs(52) = "AA5"
    vals(52) = "=CONCATENATE(TEXT(Z4,""$0""),"" - "",TEXT(Z5,""$0""),""m"")"
    refs(53) = "Z6"
    isNum(53) = True: numv(53) = 200
    refs(54) = "AA6"
    vals(54) = "=CONCATENATE(TEXT(Z5,""$0""),"" - "",TEXT(Z6,""$0""),""m"")"
    refs(55) = "Z7"
    isNum(55) = True: numv(55) = 300
    refs(56) = "AA7"
    vals(56) = "=CONCATENATE(TEXT(Z6,""$0""),"" - "",TEXT(Z7,""$0""),""m"")"
    refs(57) = "Z8"
    isNum(57) = True: numv(57) = 400
    refs(58) = "AA8"
    vals(58) = "=CONCATENATE(TEXT(Z7,""$0""),"" - "",TEXT(Z8,""$0""),""m"")"
    refs(59) = "Z9"
    vals(59) = "=Z8"
    refs(60) = "AA9"
    vals(60) = "=CONCATENATE("">="",TEXT(Z9,""$0""),""m"")"
    refs(61) = "AB3"
    vals(61) = "Revenue Buckets"
    refs(62) = "AC3"
    vals(62) = "Revenue Labels"
    refs(63) = "AB4"
    isNum(63) = True: numv(63) = 0
    refs(64) = "AC4"
    vals(64) = "=CONCATENATE(""<="",TEXT(AB4,""$0""),""m"")"
    refs(65) = "AB5"
    isNum(65) = True: numv(65) = 250
    refs(66) = "AC5"
    vals(66) = "=CONCATENATE(TEXT(AB4,""$0""),"" - "",TEXT(AB5,""$0""),""m"")"
    refs(67) = "AB6"
    isNum(67) = True: numv(67) = 500
    refs(68) = "AC6"
    vals(68) = "=CONCATENATE(TEXT(AB5,""$0""),"" - "",TEXT(AB6,""$0""),""m"")"
    refs(69) = "AB7"
    isNum(69) = True: numv(69) = 1000
    refs(70) = "AC7"
    vals(70) = "=CONCATENATE(TEXT(AB6,""$0""),"" - "",TEXT(AB7,""$0""),""m"")"
    refs(71) = "AB8"
    isNum(71) = True: numv(71) = 1500
    refs(72) = "AC8"
    vals(72) = "=CONCATENATE(TEXT(AB7,""$0""),"" - "",TEXT(AB8,""$0""),""m"")"
    refs(73) = "AB9"
    vals(73) = "=AB8"
    refs(74) = "AC9"
    vals(74) = "=CONCATENATE("">="",TEXT(AB9,""$0""),""m"")"
    refs(75) = "BA5"
    vals(75) = "Entry TEV"
    refs(76) = "BB5"
    vals(76) = "Label"
    refs(77) = "BA6"
    isNum(77) = True: numv(77) = 0
    refs(78) = "BB6"
    vals(78) = "=CONCATENATE(""<="",TEXT(BA6,""$0""),""m"")"
    refs(79) = "BA7"
    isNum(79) = True: numv(79) = 500
    refs(80) = "BB7"
    vals(80) = "=CONCATENATE(TEXT(BA6,""$0""),"" - "",TEXT(BA7,""$0""),""m"")"
    refs(81) = "BA8"
    isNum(81) = True: numv(81) = 1000
    refs(82) = "BB8"
    vals(82) = "=CONCATENATE(TEXT(BA7,""$0""),"" - "",TEXT(BA8,""$0""),""m"")"
    refs(83) = "BA9"
    isNum(83) = True: numv(83) = 1500
    refs(84) = "BB9"
    vals(84) = "=CONCATENATE(TEXT(BA8,""$0""),"" - "",TEXT(BA9,""$0""),""m"")"
    refs(85) = "BA10"
    isNum(85) = True: numv(85) = 2000
    refs(86) = "BB10"
    vals(86) = "=CONCATENATE(TEXT(BA9,""$0""),"" - "",TEXT(BA10,""$0""),""m"")"
    refs(87) = "BA11"
    vals(87) = "=BA10"
    refs(88) = "BB11"
    vals(88) = "=CONCATENATE("">="",TEXT(BA11,""$0""),""m"")"
    refs(89) = "BC5"
    vals(89) = "Entry Multiple"
    refs(90) = "BD5"
    vals(90) = "Label"
    refs(91) = "BC6"
    isNum(91) = True: numv(91) = 0
    refs(92) = "BD6"
    vals(92) = "=CONCATENATE(""<="",TEXT(BC6,""0x""))"
    refs(93) = "BC7"
    isNum(93) = True: numv(93) = 5
    refs(94) = "BD7"
    vals(94) = "=CONCATENATE(TEXT(BC6,""0x""),"" - "",TEXT(BC7,""0x""))"
    refs(95) = "BC8"
    isNum(95) = True: numv(95) = 10
    refs(96) = "BD8"
    vals(96) = "=CONCATENATE(TEXT(BC7,""0x""),"" - "",TEXT(BC8,""0x""))"
    refs(97) = "BC9"
    isNum(97) = True: numv(97) = 15
    refs(98) = "BD9"
    vals(98) = "=CONCATENATE(TEXT(BC8,""0x""),"" - "",TEXT(BC9,""0x""))"
    refs(99) = "BC10"
    isNum(99) = True: numv(99) = 20
    refs(100) = "BD10"
    vals(100) = "=CONCATENATE(TEXT(BC9,""0x""),"" - "",TEXT(BC10,""0x""))"
    refs(101) = "BC11"
    vals(101) = "=BC10"
    refs(102) = "BD11"
    vals(102) = "=CONCATENATE("">="",TEXT(BC11,""0x""))"
    refs(103) = "BE5"
    vals(103) = "Entry Margin Bucket"
    refs(104) = "BF5"
    vals(104) = "Labels"
    refs(105) = "BE6"
    isNum(105) = True: numv(105) = 0.2
    refs(106) = "BF6"
    vals(106) = "=CONCATENATE(""<="",TEXT(BE6,""0%""))"
    refs(107) = "BE7"
    isNum(107) = True: numv(107) = 0.3
    refs(108) = "BF7"
    vals(108) = "=CONCATENATE(TEXT(BE6,""0%""),"" - "",TEXT(BE7,""0%""))"
    refs(109) = "BE8"
    isNum(109) = True: numv(109) = 0.4
    refs(110) = "BF8"
    vals(110) = "=CONCATENATE(TEXT(BE7,""0%""),"" - "",TEXT(BE8,""0%""))"
    refs(111) = "BE9"
    isNum(111) = True: numv(111) = 0.5
    refs(112) = "BF9"
    vals(112) = "=CONCATENATE(TEXT(BE8,""0%""),"" - "",TEXT(BE9,""0%""))"
    refs(113) = "BE10"
    vals(113) = "=BE9"
    refs(114) = "BF10"
    vals(114) = "=CONCATENATE("">="",TEXT(BE10,""0%""))"
    refs(115) = "W8"
    vals(115) = "IRR Buckets"
    refs(116) = "X8"
    vals(116) = "IRR Labels"
    refs(117) = "W9"
    isNum(117) = True: numv(117) = 0
    refs(118) = "X9"
    vals(118) = "=CONCATENATE(""<="",TEXT(W9,""0%""))"
    refs(119) = "W10"
    isNum(119) = True: numv(119) = 0.1
    refs(120) = "X10"
    vals(120) = "=CONCATENATE(TEXT(W9,""0%""),"" - "",TEXT(W10,""0%""))"
    refs(121) = "W11"
    isNum(121) = True: numv(121) = 0.2
    refs(122) = "X11"
    vals(122) = "=CONCATENATE(TEXT(W10,""0%""),"" - "",TEXT(W11,""0%""))"
    refs(123) = "W12"
    vals(123) = "=W11"
    refs(124) = "X12"
    vals(124) = "=CONCATENATE("">="",TEXT(W12,""0%""))"
    refs(125) = "N11"
    vals(125) = "Note: no text inputs, either blank, 0 or a number"
    refs(126) = "AJ10"
    vals(126) = "Financial Metrics"
    refs(127) = "AJ11"
    vals(127) = "Entry Metrics"
    refs(128) = "AT11"
    vals(128) = "Exit/Current Metrics"
End Sub

Public Sub LoadPivotSpecs(title() As String, fld() As String, variant_() As String)
    ReDim title(1 To 15): ReDim fld(1 To 15)
    ReDim variant_(1 To 15)
    title(1) = "Gross Returns & Loss Ratios by Sector"
    fld(1) = "Sector"
    variant_(1) = ""
    title(2) = "Gross Returns & Loss Ratios by Geography"
    fld(2) = "Geography"
    variant_(2) = ""
    title(3) = "Gross Returns & Loss Ratios by Process Type"
    fld(3) = "Process Type"
    variant_(3) = ""
    title(4) = "Gross Returns & Loss Ratios by GP Role"
    fld(4) = "GP Role"
    variant_(4) = ""
    title(5) = "Gross Returns & Loss Ratios by Exit Type"
    fld(5) = "Exit Type"
    variant_(5) = ""
    title(6) = "Gross Returns & Loss Ratios by Entry Revenue"
    fld(6) = "Revenue Buckets"
    variant_(6) = ""
    title(7) = "Gross Returns & Loss Ratios by Entry EBITDA"
    fld(7) = "EBITDA Buckets"
    variant_(7) = ""
    title(8) = "Gross Returns & Loss Ratios by Entry EBITDA Multiple"
    fld(8) = "Entry Multiple Bucket"
    variant_(8) = ""
    title(9) = "Impaired Loss Ratios by Entry Enterprise Value"
    fld(9) = "Entry Enterprise" & Chr(10) & "ValueBuckets"
    variant_(9) = "impaired"
    title(10) = "Gross Returns & Loss Ratios by Vintage"
    fld(10) = "Vintage"
    variant_(10) = ""
    title(11) = "Capital Deployment & Returns by Vintage"
    fld(11) = "Vintage"
    variant_(11) = "with_ic"
    title(12) = "Gross Returns & Loss Ratios by Entry EBITDA Margin"
    fld(12) = "Entry EBITDA Margin Bucket"
    variant_(12) = ""
    title(13) = "Gross Returns & Loss Ratios by Initial Invested Capital"
    fld(13) = "Initial InvCap Buckets"
    variant_(13) = ""
    title(14) = "Gross Returns & Loss Ratios by COI Deals"
    fld(14) = "COI Deal (Yes/No)"
    variant_(14) = ""
    title(15) = "Gross Returns & Loss Ratios by Fund"
    fld(15) = "Fund"
    variant_(15) = ""
End Sub

Public Sub LoadPageFields(p() As String)
    ReDim p(1 To 3)
    p(1) = "Fund"
    p(2) = "Status"
    p(3) = "Hold Period Buckets"
End Sub

' Canonical display order for bucket axes (native pivots would otherwise
' sort alphabetically). Returns Empty when the field has no fixed order.
Public Function CanonicalOrder(ByVal fieldName As String) As Variant
    Select Case fieldName
        Case "Revenue Buckets"
            CanonicalOrder = Array("<=$0m", "$0 - $250m", "$250 - $500m", "$500 - $1000m", "$1000 - $1500m", ">=$1500m")
        Case "EBITDA Buckets"
            CanonicalOrder = Array("<=$0m", "$0 - $100m", "$100 - $200m", "$200 - $300m", "$300 - $400m", ">=$400m")
        Case "Entry Multiple Bucket"
            CanonicalOrder = Array("<=0x", "0x - 5x", "5x - 10x", "10x - 15x", "15x - 20x", ">=20x")
        Case "Entry EBITDA Margin Bucket"
            CanonicalOrder = Array("<=20%", "20% - 30%", "30% - 40%", "40% - 50%", ">=50%")
        Case "Entry Enterprise" & Chr(10) & "ValueBuckets"
            CanonicalOrder = Array("<=$0m", "$0 - $500m", "$500 - $1000m", "$1000 - $1500m", "$1500 - $2000m", ">=$2000m")
        Case "Initial InvCap Buckets"
            CanonicalOrder = Array("<=$250m", "$250 - $500m", "$500 - $1000m", "$1000 - $1250m", "$1250 - $1500m", ">=$1500m")
        Case "Hold Period Buckets"
            CanonicalOrder = Array("<=2 yrs", "2 yrs  - 4 yrs", "4 yrs  - 6 yrs", "6 yrs  - 8 yrs", ">=8 yrs")
        Case "Status"
            CanonicalOrder = Array("Realized", "Unrealized")
        Case "MOIC Buckets"
            CanonicalOrder = Array("<=1.0x", "1.0x - 2.0x", "2.0x - 3.0x", ">=3.0x")
        Case "IRR Buckets"
            CanonicalOrder = Array("<=0%", "0% - 10%", "10% - 20%", ">=20%")
        Case Else
            CanonicalOrder = Empty
    End Select
End Function
