"""
deal_list_spec.py — exact Deal List schema: the Segmented Track Record
Analysis Output template layout as revised per Eric Lees' feedback
(Jul 2026 "EWL Edits" workbook): 57 columns B..BF (the template's
'Unique Identifier' column and the whole IC-weighted/CAGR block
AdjInvCapRevenueCAGR..WghtedEntryEquityMultiple removed), tag row 12, header row 13, data
from row 14.

Formulas are the template's, with mechanical adaptations for our
linked-input model (links return "" for blanks, ISBLANK() cannot see them):
  - ISBLANK(x) -> (x="")
  - the unguarded arithmetic columns (Total Value, Entry Equity Value)
    use N()-guarded equivalents so "" behaves like a blank cell
  - Hold Period carries {r} row placeholders (the template text froze its
    relative refs at the first data row; the dead #REF! branch is the
    template's own)
"""

# (header, src, transformer_key, cache_kind)
#   src: "in:<Deal Level Inputs header>" | "FT:<template formula, verbatim
#        table-structured>" | "F:<formula with {r} row placeholder>" |
DL_COLS: list[tuple[str, str, int, str]] = [
    ('Company', 'in:Company', 1, 'g'),
    ('Fund', 'in:Fund', 2, 'g'),
    ('Fund Currency', 'in:Fund Currency', 90, 'g'),
    ('Vintage', 'F:IF((DealLevelInput[[#This Row],[Inv. Date]]=""),"n/a",YEAR(G{r}))', 4, 'gn'),
    ('Status', 'in:Status', 5, 'g'),
    ('Inv. Date', 'in:Inv. Date', 6, 'dt'),
    ('Exit Date', 'in:Exit Date', 7, 'dt'),
    ('Exit Year', 'FT:IF((DealLevelInput[[#This Row],[Exit Date]]=""),"n/a",YEAR(DealLevelInput[[#This Row],[Exit Date]]))', 8, 'gn'),
    ('Hold\nPeriod', 'F:IF((DealLevelInput[[#This Row],[Exit Date]]=""),"n/a",IF(ISNUMBER(H{r}),H{r}-G{r},NA()-G{r})/365)', 9, 'n'),
    ('Hold Period Buckets', 'FT:IF((DealLevelInput[[#This Row],[Inv. Date]]=""),"n/a",IF(DealLevelInput[[#This Row],[Hold\nPeriod]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Hold\nPeriod]]<$J$7,$K$7,IF(DealLevelInput[[#This Row],[Hold\nPeriod]]<$J$8,$K$8,IF(DealLevelInput[[#This Row],[Hold\nPeriod]]<$J$9,$K$9,IF(DealLevelInput[[#This Row],[Hold\nPeriod]]<$J$10,$K$10,$K$11))))))', 10, 'g'),
    ('Sector', 'in:Sector', 11, 'g'),
    ('Geography', 'in:Geography', 12, 'g'),
    ('Total IC mlns for Buckets', 'FT:IF((DealLevelInput[[#This Row],[Total Invested Capital (mlns)]]=""),0,DealLevelInput[[#This Row],[Total Invested Capital (mlns)]])', 14, 'n'),
    ('Initial InvCap Buckets', 'FT:IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$7,$O$7,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$8,$O$8,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$9,$O$9,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$10,$O$10,IF(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]<=$N$11,$O$11,$O$12))))))', 15, 'g'),
    ('Total Invested Capital (mlns)', 'in:Total Invested Capital (mlns)', 16, 'n'),
    ('Realized\nValue', 'in0:Realized\nValue', 17, 'n'),
    ('Current\nValue', 'in:Current\nValue', 18, 'n'),
    ('Total\nValue', 'F:IF(AND(Q{r}="",R{r}=""),"",N(Q{r})+N(R{r}))', 19, 'n'),
    ('Gross\nMOIC', 'FT:IFERROR(DealLevelInput[[#This Row],[Total\nValue]]/DealLevelInput[[#This Row],[Total Invested Capital (mlns)]],"n/a")', 20, 'n'),
    ('MOIC Buckets', 'FT:IF(DealLevelInput[[#This Row],[Gross\nMOIC]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Gross\nMOIC]]<=$T$9,$U$9,IF(DealLevelInput[[#This Row],[Gross\nMOIC]]<=$T$10,$U$10,IF(DealLevelInput[[#This Row],[Gross\nMOIC]]<=$T$11,$U$11,$U$12))))', 21, 'g'),
    ('Performing\n(1=Underperform)', 'FT:IF(DealLevelInput[[#This Row],[Gross\nMOIC]]<1,1,"-")', 22, 'gn'),
    ('InvCapital in Loss Position', 'FT:IF(DealLevelInput[[#This Row],[Gross\nMOIC]]<1,DealLevelInput[[#This Row],[Total Invested Capital (mlns)]],0)', 23, 'n'),
    ('Impaired\nValue', 'FT:IF(DealLevelInput[[#This Row],[Gross\nMOIC]]<1,(1-DealLevelInput[[#This Row],[Gross\nMOIC]])*DealLevelInput[[#This Row],[Total IC mlns for Buckets]],0)', 24, 'n'),
    ('Entry EBITDA', 'FT:IF((DealLevelInput[[#This Row],[Entry LTM\nEBITDA]]=""),"n/a",DealLevelInput[[#This Row],[Entry LTM\nEBITDA]])', 25, 'n'),
    ('EBITDA Buckets', 'FT:IF(DealLevelInput[[#This Row],[Entry EBITDA]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$4,$AA$4,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$5,$AA$5,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$6,$AA$6,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$7,$AA$7,IF(DealLevelInput[[#This Row],[Entry EBITDA]]<=$Z$8,$AA$8,$AA$9))))))', 26, 'g'),
    ('Entry Revenue', 'FT:IF((DealLevelInput[[#This Row],[Entry LTM Revenue]]=""),"n/a",DealLevelInput[[#This Row],[Entry LTM Revenue]])', 27, 'n'),
    ('Revenue Buckets', 'FT:IF(DealLevelInput[[#This Row],[Entry Revenue]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$4,$AC$4,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$5,$AC$5,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$6,$AC$6,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$7,$AC$7,IF(DealLevelInput[[#This Row],[Entry Revenue]]<=$AB$8,$AC$8,$AC$9))))))', 28, 'g'),
    ('Transaction Type', 'in:Transaction Type', 29, 'g'),
    ('GP Role', 'in:GP Role', 30, 'g'),
    ('Process Type', 'in:Process Type', 31, 'g'),
    ('Sourcing Partner', 'in:Sourcing Partner', 32, 'g'),
    ('Exit Type', 'in:Exit Type', 33, 'g'),
    ('COI Deal (Yes/No)', 'in:COI Deal (Yes/No)', 34, 'g'),
    ('Gross\nIRR', 'in:Gross\nIRR', 35, 'n'),
    ('Entry LTM Revenue', 'in:Entry LTM\nRevenue', 36, 'n'),
    ('Entry LTM\nEBITDA', 'in:Entry LTM\nEBITDA', 37, 'n'),
    ('Entry\nEBITDA Margin', 'FT:IFERROR(DealLevelInput[[#This Row],[Entry LTM\nEBITDA]]/DealLevelInput[[#This Row],[Entry LTM Revenue]],"n/a")', 38, 'n'),
    ('Entry\nNet Debt', 'in:Entry\nNet Debt', 39, 'n'),
    ('Entry Leverage', 'FT:IFERROR(DealLevelInput[[#This Row],[Entry\nNet Debt]]/DealLevelInput[[#This Row],[Entry LTM\nEBITDA]],"n/a")', 40, 'n'),
    ('Entry\nEquity\nValue', 'F:IF(AND(AP{r}="",AM{r}=""),"",N(AP{r})-N(AM{r}))', 41, 'n'),
    ('Entry Enterprise\nValue', 'in:Entry Enterprise\nValue', 42, 'n'),
    ('Entry\nEBITDA Multiple', 'FT:IFERROR(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]/DealLevelInput[[#This Row],[Entry LTM\nEBITDA]],"n/a")', 43, 'n'),
    ('Entry Equity Multiple', 'FT:IFERROR(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]-DealLevelInput[[#This Row],[Entry Leverage]],"n/a")', 44, 'n'),
    ('Entry EV Sales Multiple', 'FT:IFERROR(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]/DealLevelInput[[#This Row],[Entry LTM Revenue]],"n/a")', 45, 'n'),
    ('Exit LTM\nRevenue', 'in:Exit LTM\nRevenue', 46, 'n'),
    ('Exit LTM\nEBITDA', 'in:Exit LTM\nEBITDA', 47, 'n'),
    ('Exit\nEBITDA Margin', 'FT:IFERROR(DealLevelInput[[#This Row],[Exit LTM\nEBITDA]]/DealLevelInput[[#This Row],[Exit LTM\nRevenue]],"n/a")', 48, 'n'),
    ('Exit\nNet Debt', 'in:Exit\nNet Debt', 49, 'n'),
    ('Exit Leverage', 'FT:IFERROR(DealLevelInput[[#This Row],[Exit\nNet Debt]]/DealLevelInput[[#This Row],[Exit LTM\nEBITDA]],"n/a")', 50, 'n'),
    ('Exit\nEquity Value', 'FT:IFERROR(DealLevelInput[[#This Row],[Exit Enterprise Value]]-DealLevelInput[[#This Row],[Exit\nNet Debt]],"n/a")', 51, 'n'),
    ('Exit Enterprise Value', 'in:Exit Enterprise Value', 52, 'n'),
    ('Exit EBITDA Multiple', 'FT:IFERROR(DealLevelInput[[#This Row],[Exit Enterprise Value]]/DealLevelInput[[#This Row],[Exit LTM\nEBITDA]],"n/a")', 53, 'n'),
    ('Exit EV Sales Multiple', 'FT:IFERROR(DealLevelInput[[#This Row],[Exit Enterprise Value]]/DealLevelInput[[#This Row],[Exit LTM\nRevenue]],"n/a")', 54, 'n'),
    ('Valuation Method', 'in:Valuation Method', 55, 's'),
    ('Entry Enterprise\nValueBuckets', 'FT:IF(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]<=$BA$6,$BB$6,IF(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]<=$BA$7,$BB$7,IF(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]<=$BA$8,$BB$8,IF(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]<=$BA$9,$BB$9,IF(DealLevelInput[[#This Row],[Entry Enterprise\nValue]]<=$BA$10,$BB$10,$BB$11))))))', 56, 'g'),
    ('Entry Multiple Bucket', 'FT:IF(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]<=$BC$6,$BD$6,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]<=$BC$7,$BD$7,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]<=$BC$8,$BD$8,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]<=$BC$9,$BD$9,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]<=$BC$10,$BD$10,$BD$11))))))', 57, 'g'),
    ('Entry EBITDA Margin Bucket', 'FT:IF(DealLevelInput[[#This Row],[Entry\nEBITDA Margin]]="n/a","n/a",IF(DealLevelInput[[#This Row],[Entry\nEBITDA Margin]]<=$BE$6,$BF$6,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Margin]]<=$BE$7,$BF$7,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Margin]]<=$BE$8,$BF$8,IF(DealLevelInput[[#This Row],[Entry\nEBITDA Margin]]<=$BE$9,$BF$9,$BF$10)))))', 58, 'g'),
    ('IRR Buckets', 'FT:IF((DealLevelInput[[#This Row],[Gross\nIRR]]=""),"n/a",IF(DealLevelInput[[#This Row],[Gross\nIRR]]<=$W$9,$X$9,IF(DealLevelInput[[#This Row],[Gross\nIRR]]<=$W$10,$X$10,IF(DealLevelInput[[#This Row],[Gross\nIRR]]<=$W$11,$X$11,$X$12))))', 35, 'g'),
    ('AdjInvCapRevenueCAGR', 'FT:DealLevelInput[[#This Row],[Total IC mlns for Buckets]]', 59, 'n'),
    ('Revenue CAGR', 'FT:IFERROR((DealLevelInput[[#This Row],[Exit LTM\nRevenue]]/DealLevelInput[[#This Row],[Entry LTM Revenue]])^(1/DealLevelInput[[#This Row],[Hold\nPeriod]])-1,"n/a")', 60, 'n'),
    ('WghtdRevCAGR', 'FT:IFERROR(DealLevelInput[[#This Row],[Revenue CAGR]]*DealLevelInput[[#This Row],[AdjInvCapRevenueCAGR]],"n/a")', 61, 'n'),
    ('AdjInvCapEBITDAcagr', 'FT:DealLevelInput[[#This Row],[Total IC mlns for Buckets]]', 62, 'n'),
    ('EBITDA CAGR', 'FT:IFERROR((DealLevelInput[[#This Row],[Exit LTM\nEBITDA]]/DealLevelInput[[#This Row],[Entry EBITDA]])^(1/DealLevelInput[[#This Row],[Hold\nPeriod]])-1,"n/a")', 63, 'n'),
    ('WghtdEBITDAcagr', 'FT:IFERROR(DealLevelInput[[#This Row],[EBITDA CAGR]]*DealLevelInput[[#This Row],[AdjInvCapEBITDAcagr]],"n/a")', 64, 'n'),
    ('AdjInvCapEBITDAMargin', 'FT:DealLevelInput[[#This Row],[Total IC mlns for Buckets]]', 65, 'n'),
    ('Wgtd Entry EBITDA Margin', 'FT:IFERROR((DealLevelInput[[#This Row],[AdjInvCapEBITDAMargin]]*DealLevelInput[[#This Row],[Entry\nEBITDA Margin]]),"n/a")', 66, 'n'),
    ('Wgtd Current EBITDA Margin', 'FT:IFERROR((DealLevelInput[[#This Row],[Total IC mlns for Buckets]]*DealLevelInput[[#This Row],[Exit\nEBITDA Margin]]),"n/a")', 67, 'n'),
    ('Wghtd Hold Period', 'FT:IFERROR(DealLevelInput[[#This Row],[Total IC mlns for Buckets]]*DealLevelInput[[#This Row],[Hold\nPeriod]],"n/a")', 68, 'n'),
    ('AdjInvCapMultiples', 'FT:IF(OR(DealLevelInput[[#This Row],[Exit EBITDA Multiple]]=0,DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]=0),0,DealLevelInput[[#This Row],[Total IC mlns for Buckets]])', 69, 'n'),
    ('WgtdEntryMultiple', 'FT:IFERROR((DealLevelInput[[#This Row],[AdjInvCapMultiples]]*DealLevelInput[[#This Row],[Entry\nEBITDA Multiple]]),"n/a")', 70, 'n'),
    ('WghtdExitMultiple', 'FT:IFERROR((DealLevelInput[[#This Row],[AdjInvCapMultiples]]*DealLevelInput[[#This Row],[Exit EBITDA Multiple]]),"n/a")', 71, 'n'),
    ('AdjInvCapLeverage', 'FT:IF(OR(DealLevelInput[[#This Row],[Entry Leverage]]="n/a",DealLevelInput[[#This Row],[Exit Leverage]]="n/a"),0,DealLevelInput[[#This Row],[Total IC mlns for Buckets]])', 72, 'n'),
    ('WghtdEntryLeverage', 'FT:IFERROR(DealLevelInput[[#This Row],[AdjInvCapLeverage]]*DealLevelInput[[#This Row],[Entry Leverage]],"n/a")', 73, 'n'),
    ('WghtdExitLeverage', 'FT:IFERROR(DealLevelInput[[#This Row],[AdjInvCapLeverage]]*DealLevelInput[[#This Row],[Exit Leverage]],"n/a")', 74, 'n'),
]

# Data-row number formats {column_index0: fmt}
DL_FORMATS: dict[int, str] = {3: '####', 4: '####', 5: 'dd\\-mmm\\-yy', 6: 'dd\\-mmm\\-yy', 7: '####', 8: '0.0\\ "years"', 9: '0.0\\ "years"', 12: '###,###,###;\\(###,###,###\\);"-"', 13: '"$"###,###,###;\\("$"###,###,###\\);"-"', 14: '###,###,###;\\(###,###,###\\);"-"', 15: '###,###,###;\\(###,###,###\\);"-"', 16: '###,###,###;\\(###,###,###\\);"-"', 17: '###,###,###;\\(###,###,###\\);"-"', 18: '0.0\\x;\\(0.0\\x\\);"-"', 19: '0.0%', 20: '0.0;\\(0.0\\);"-"', 21: '"$"###,###,###;\\("$"###,###,###\\);"-"', 22: '"$"###,###,###;\\("$"###,###,###\\);"-"', 23: '###,###,###.0;\\(###,###,###.0\\);"-"', 24: '"$"###,###,###;\\("$"###,###,###\\);"-"', 25: '###,###,###.0;\\(###,###,###.0\\);"-"', 26: '"$"###,###,###;\\("$"###,###,###\\);"-"', 30: '0.00%', 31: '0.00%', 32: '0.00%', 33: '0.0%', 34: '###,###.0;\\(###,###.0\\);"-"', 35: '###,###.0;\\(###,###.0\\);"-"', 36: '0.0%', 37: '###,###.0;\\(###,###.0\\);"-"', 38: '0.0\\x;\\(0.0\\x\\);"-"', 39: '###,###.0;\\(###,###.0\\);"-"', 40: '###,###.0;\\(###,###.0\\);"-"', 41: '0.0\\x', 42: '0.0\\x', 43: '0.0\\x', 44: '###,###.0;\\(###,###.0\\);"-"', 45: '###,###.0;\\(###,###.0\\);"-"', 46: '0.0%', 47: '###,###.0;\\(###,###.0\\);"-"', 48: '0.0\\x;\\(0.0\\x\\);"-"', 49: '###,###.0;\\(###,###.0\\);"-"', 50: '###,###.0;\\(###,###.0\\);"-"', 51: '0.0\\x', 52: '0.0\\x', 53: '0.0\\x', 54: '"$"###,###,###;\\("$"###,###,###\\);"-"', 55: '"$"###,###,###;\\("$"###,###,###\\);"-"', 56: '"$"###,###,###;\\("$"###,###,###\\);"-"', 58: '#,##0', 59: '0.0%', 60: '#,##0', 61: '#,##0', 62: '0.0%', 63: '#,##0', 64: '#,##0', 65: '#,##0', 66: '#,##0', 67: '#,##0', 68: '#,##0', 69: '#,##0', 70: '#,##0', 71: '#,##0', 72: '#,##0', 73: '#,##0'}

# Row-12 column tags (Eric: Input / Formula / Entry / Exit markers)
TAG_ROW: list[tuple[str, str]] = [('B', 'Input'), ('C', 'Input'), ('D', 'Input'), ('E', 'Input'), ('F', 'Input'), ('G', 'Input'), ('H', 'Formula'), ('I', 'Formula'), ('J', 'Formula'), ('K', 'Formula'), ('AJ', 'Entry'), ('AK', 'Entry'), ('AL', 'Entry'), ('AM', 'Entry'), ('AN', 'Entry'), ('AO', 'Entry'), ('AP', 'Entry'), ('AQ', 'Entry'), ('AR', 'Entry'), ('AS', 'Entry'), ('AT', 'Exit'), ('AU', 'Exit'), ('AV', 'Exit'), ('AW', 'Exit'), ('AX', 'Exit'), ('AY', 'Exit'), ('AZ', 'Exit'), ('BA', 'Exit'), ('BB', 'Exit')]

# Header block cells (rows 1-12). "{LAST}" -> last data row at build time.
HEADER_BLOCK: list[dict] = [
    {'ref': 'B2', 'v': 'Deal List', 'fmt': None, 'bold': True},
    {'ref': 'B4', 'v': 'Sponsor/GP:', 'fmt': 'mm-dd-yy', 'bold': False},
    {'ref': 'B5', 'v': 'As of Date:', 'fmt': 'mm-dd-yy', 'bold': False},
    {'ref': 'B6', 'v': 'Currency:', 'fmt': 'mm-dd-yy', 'bold': False},
    {'ref': 'E9', 'v': 'Number of', 'fmt': None, 'bold': False},
    {'ref': 'F9', 'v': 'Realized', 'fmt': None, 'bold': False},
    {'ref': 'E10', 'v': 'Deals', 'fmt': None, 'bold': False},
    {'ref': 'F10', 'v': 'Deals', 'fmt': None, 'bold': False},
    {'ref': 'E11', 'v': '=COUNTA(DealLevelInput[Company])', 'fmt': None, 'bold': False},
    {'ref': 'F11', 'v': '=COUNTIF($F$14:$F${LAST},F9)', 'fmt': None, 'bold': False},
    {'ref': 'J6', 'v': 'Hold Period', 'fmt': None, 'bold': False},
    {'ref': 'K6', 'v': 'HP Buckets', 'fmt': None, 'bold': False},
    {'ref': 'J7', 'v': 2, 'fmt': '0.0', 'bold': False},
    {'ref': 'K7', 'v': '=CONCATENATE("<=",TEXT(J7,"0")," yrs")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'J8', 'v': 4, 'fmt': '0.0', 'bold': False},
    {'ref': 'K8', 'v': '=CONCATENATE(TEXT(J7,"0")," yrs  - ",TEXT(J8,"0")," yrs")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'J9', 'v': 6, 'fmt': '0.0', 'bold': False},
    {'ref': 'K9', 'v': '=CONCATENATE(TEXT(J8,"0")," yrs  - ",TEXT(J9,"0")," yrs")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'J10', 'v': 8, 'fmt': '0.0', 'bold': False},
    {'ref': 'K10', 'v': '=CONCATENATE(TEXT(J9,"0")," yrs  - ",TEXT(J10,"0")," yrs")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'J11', 'v': '=J10', 'fmt': '0.0', 'bold': False},
    {'ref': 'K11', 'v': '=CONCATENATE(">=",TEXT(J11,"0")," yrs")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N6', 'v': 'Inv Cap Buckets', 'fmt': None, 'bold': False},
    {'ref': 'O6', 'v': 'Inv Cap Labels', 'fmt': None, 'bold': False},
    {'ref': 'N7', 'v': 250, 'fmt': '0', 'bold': False},
    {'ref': 'O7', 'v': '=CONCATENATE("<=",TEXT(N7,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N8', 'v': 500, 'fmt': '0', 'bold': False},
    {'ref': 'O8', 'v': '=CONCATENATE(TEXT(N7,"$0")," - ",TEXT(N8,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N9', 'v': 1000, 'fmt': '0', 'bold': False},
    {'ref': 'O9', 'v': '=CONCATENATE(TEXT(N8,"$0")," - ",TEXT(N9,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N10', 'v': 1250, 'fmt': '0', 'bold': False},
    {'ref': 'O10', 'v': '=CONCATENATE(TEXT(N9,"$0")," - ",TEXT(N10,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N11', 'v': 1500, 'fmt': '0', 'bold': False},
    {'ref': 'O11', 'v': '=CONCATENATE(TEXT(N10,"$0")," - ",TEXT(N11,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N12', 'v': '=N11', 'fmt': '0', 'bold': False},
    {'ref': 'O12', 'v': '=CONCATENATE(">=",TEXT(N12,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'T8', 'v': 'MOIC Buckets', 'fmt': None, 'bold': False},
    {'ref': 'U8', 'v': 'MOIC Labels', 'fmt': None, 'bold': False},
    {'ref': 'T9', 'v': 1, 'fmt': '0.0', 'bold': False},
    {'ref': 'U9', 'v': '=CONCATENATE("<=",TEXT(T9,"0.0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'T10', 'v': 2, 'fmt': '0.0', 'bold': False},
    {'ref': 'U10', 'v': '=CONCATENATE(TEXT(T9,"0.0x")," - ",TEXT(T10,"0.0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'T11', 'v': 3, 'fmt': '0.0', 'bold': False},
    {'ref': 'U11', 'v': '=CONCATENATE(TEXT(T10,"0.0x")," - ",TEXT(T11,"0.0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'T12', 'v': '=T11', 'fmt': '0.0', 'bold': False},
    {'ref': 'U12', 'v': '=CONCATENATE(">=",TEXT(T12,"0.0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'Z3', 'v': 'EBITDA Buckets', 'fmt': None, 'bold': False},
    {'ref': 'AA3', 'v': 'EBITDA Labels', 'fmt': None, 'bold': False},
    {'ref': 'Z4', 'v': 0, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AA4', 'v': '=CONCATENATE("<=",TEXT(Z4,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'Z5', 'v': 100, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AA5', 'v': '=CONCATENATE(TEXT(Z4,"$0")," - ",TEXT(Z5,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'Z6', 'v': 200, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AA6', 'v': '=CONCATENATE(TEXT(Z5,"$0")," - ",TEXT(Z6,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'Z7', 'v': 300, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AA7', 'v': '=CONCATENATE(TEXT(Z6,"$0")," - ",TEXT(Z7,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'Z8', 'v': 400, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AA8', 'v': '=CONCATENATE(TEXT(Z7,"$0")," - ",TEXT(Z8,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'Z9', 'v': '=Z8', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AA9', 'v': '=CONCATENATE(">=",TEXT(Z9,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AB3', 'v': 'Revenue Buckets', 'fmt': None, 'bold': False},
    {'ref': 'AC3', 'v': 'Revenue Labels', 'fmt': None, 'bold': False},
    {'ref': 'AB4', 'v': 0, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AC4', 'v': '=CONCATENATE("<=",TEXT(AB4,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AB5', 'v': 250, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AC5', 'v': '=CONCATENATE(TEXT(AB4,"$0")," - ",TEXT(AB5,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AB6', 'v': 500, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AC6', 'v': '=CONCATENATE(TEXT(AB5,"$0")," - ",TEXT(AB6,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AB7', 'v': 1000, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AC7', 'v': '=CONCATENATE(TEXT(AB6,"$0")," - ",TEXT(AB7,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AB8', 'v': 1500, 'fmt': '"$"0', 'bold': False},
    {'ref': 'AC8', 'v': '=CONCATENATE(TEXT(AB7,"$0")," - ",TEXT(AB8,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AB9', 'v': '=AB8', 'fmt': '"$"0', 'bold': False},
    {'ref': 'AC9', 'v': '=CONCATENATE(">=",TEXT(AB9,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BA5', 'v': 'Entry TEV', 'fmt': None, 'bold': False},
    {'ref': 'BB5', 'v': 'Label', 'fmt': None, 'bold': False},
    {'ref': 'BA6', 'v': 0, 'fmt': '"$"0', 'bold': False},
    {'ref': 'BB6', 'v': '=CONCATENATE("<=",TEXT(BA6,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BA7', 'v': 500, 'fmt': '"$"0', 'bold': False},
    {'ref': 'BB7', 'v': '=CONCATENATE(TEXT(BA6,"$0")," - ",TEXT(BA7,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BA8', 'v': 1000, 'fmt': '"$"0', 'bold': False},
    {'ref': 'BB8', 'v': '=CONCATENATE(TEXT(BA7,"$0")," - ",TEXT(BA8,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BA9', 'v': 1500, 'fmt': '"$"0', 'bold': False},
    {'ref': 'BB9', 'v': '=CONCATENATE(TEXT(BA8,"$0")," - ",TEXT(BA9,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BA10', 'v': 2000, 'fmt': '"$"0', 'bold': False},
    {'ref': 'BB10', 'v': '=CONCATENATE(TEXT(BA9,"$0")," - ",TEXT(BA10,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BA11', 'v': '=BA10', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BB11', 'v': '=CONCATENATE(">=",TEXT(BA11,"$0"),"m")', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BC5', 'v': 'Entry Multiple', 'fmt': None, 'bold': False},
    {'ref': 'BD5', 'v': 'Label', 'fmt': None, 'bold': False},
    {'ref': 'BC6', 'v': 0, 'fmt': '0\\x', 'bold': False},
    {'ref': 'BD6', 'v': '=CONCATENATE("<=",TEXT(BC6,"0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BC7', 'v': 5, 'fmt': '0\\x', 'bold': False},
    {'ref': 'BD7', 'v': '=CONCATENATE(TEXT(BC6,"0x")," - ",TEXT(BC7,"0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BC8', 'v': 10, 'fmt': '0\\x', 'bold': False},
    {'ref': 'BD8', 'v': '=CONCATENATE(TEXT(BC7,"0x")," - ",TEXT(BC8,"0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BC9', 'v': 15, 'fmt': '0\\x', 'bold': False},
    {'ref': 'BD9', 'v': '=CONCATENATE(TEXT(BC8,"0x")," - ",TEXT(BC9,"0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BC10', 'v': 20, 'fmt': '0\\x', 'bold': False},
    {'ref': 'BD10', 'v': '=CONCATENATE(TEXT(BC9,"0x")," - ",TEXT(BC10,"0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BC11', 'v': '=BC10', 'fmt': '0\\x', 'bold': False},
    {'ref': 'BD11', 'v': '=CONCATENATE(">=",TEXT(BC11,"0x"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BE5', 'v': 'Entry Margin Bucket', 'fmt': None, 'bold': False},
    {'ref': 'BF5', 'v': 'Labels', 'fmt': None, 'bold': False},
    {'ref': 'BE6', 'v': 0.2, 'fmt': '0%', 'bold': False},
    {'ref': 'BF6', 'v': '=CONCATENATE("<=",TEXT(BE6,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BE7', 'v': 0.3, 'fmt': '0%', 'bold': False},
    {'ref': 'BF7', 'v': '=CONCATENATE(TEXT(BE6,"0%")," - ",TEXT(BE7,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BE8', 'v': 0.4, 'fmt': '0%', 'bold': False},
    {'ref': 'BF8', 'v': '=CONCATENATE(TEXT(BE7,"0%")," - ",TEXT(BE8,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BE9', 'v': 0.5, 'fmt': '0%', 'bold': False},
    {'ref': 'BF9', 'v': '=CONCATENATE(TEXT(BE8,"0%")," - ",TEXT(BE9,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'BE10', 'v': '=BE9', 'fmt': '0%', 'bold': False},
    {'ref': 'BF10', 'v': '=CONCATENATE(">=",TEXT(BE10,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'W8', 'v': 'IRR Buckets', 'fmt': None, 'bold': False},
    {'ref': 'X8', 'v': 'IRR Labels', 'fmt': None, 'bold': False},
    {'ref': 'W9', 'v': 0, 'fmt': '0%', 'bold': False},
    {'ref': 'X9', 'v': '=CONCATENATE("<=",TEXT(W9,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'W10', 'v': 0.1, 'fmt': '0%', 'bold': False},
    {'ref': 'X10', 'v': '=CONCATENATE(TEXT(W9,"0%")," - ",TEXT(W10,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'W11', 'v': 0.2, 'fmt': '0%', 'bold': False},
    {'ref': 'X11', 'v': '=CONCATENATE(TEXT(W10,"0%")," - ",TEXT(W11,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'W12', 'v': '=W11', 'fmt': '0%', 'bold': False},
    {'ref': 'X12', 'v': '=CONCATENATE(">=",TEXT(W12,"0%"))', 'fmt': '"$"0', 'bold': False},
    {'ref': 'N11', 'v': 'Note: no text inputs, either blank, 0 or a number', 'fmt': None, 'bold': True},
    {'ref': 'AJ10', 'v': 'Financial Metrics', 'fmt': None, 'bold': True},
    {'ref': 'AJ11', 'v': 'Entry Metrics', 'fmt': None, 'bold': True},
    {'ref': 'AT11', 'v': 'Exit/Current Metrics', 'fmt': None, 'bold': True},
]
